### PR TITLE
initial try at read replica support

### PR DESCRIPTION
**Pull request by hakamadare**

### CODE REVIEW

**Comment by hakamadare** [comment]
hey @antonbabenko let me know what you think of this; i want to start managing read replicas with this module, and so i've put together an initial implementation that seems reasonably straightfoward

**Review by antonbabenko — COMMENTED** [review]
@hakamadare Sorry for the delay with code review (conferences, work, you know). In general, I think this code can be merged as is, but I have some architectural suggestions, which I think will lead to higher quality with current limitations of Terraform:
* Split code into two submodules:
  - normal db instance (the code as it was before your PR)
  - replica db instances (the code is mostly from replicas.tf)
* Keep `main.tf`, `outputs.tf` and `variables.tf` in the root. `main.tf` invokes two of these submodules and passes all arguments OR invoke just normal db instance module, which is there now. I don't know what is best at the moment.

By making these changes it will become possible to create db and replicas in various configurations without taking care of ordering and be afraid of losing data. The data structures will become simplified.

**Comment by hakamadare** [comment]
no worries!  ok, i'll do that; i've also come to the conclusion that it's not currently possible (due to Terraform limitations, see https://github.com/hashicorp/terraform/issues/15762 and other issues referenced from there) to write a sufficiently generic module that permits the creation of read replicas in arbitrary other regions.   i was able to provision a cross-region read replica, but only by creating every resource by hand (_i.e._ not with this module); the issue is fundamentally that i would potentially need a different version of the `aws` provider for each region, and the `provider` parameter cannot interpolate variables.

so i will rework this according to your suggestion, and remove references to cross-region replication for the time being.

**Comment by antonbabenko** [comment]
@hakamadare Feel free to implement replica sets as part of https://github.com/terraform-aws-modules/terraform-aws-rds . Closing this issue here for now, if you don't mind.

**Pull request closed without merging**
