### PR TITLE
Change type of private_cidr to list

### PR DESCRIPTION
**Pull request by trungnguyen**
Current type of var.private_cidr is a string. If I have multiple private subnets I'd like var.private_cidr to be a list

### CODE REVIEW

**Comment by hakamadare** [comment]
hey @antonbabenko would you mind taking a look at this PR?  it would be also useful to me; i'd be willing to co-maintain this repo if you'd like.

**Comment by antonbabenko** [comment]
lgtm

**Comment by antonbabenko** [comment]
@hakamadare you should be able to maintain it now. Thanks!

**Comment by hakamadare** [comment]
@trungnguyen merged!  thank you for your contribution 😁

**Pull request merged**
