### PR TITLE
Allow using an externally defined db parameter group

### LINKED ISSUE #29: Setting aws_db_parameter_group per RDS instance
Hey all!
I've been bumping against this for some time now and haven't found any satisfying solution.

I'm running several RDS instances (Postgres and MySQL). Default parameter group settings were fine until now. I'd like to override some settings on one of the RDS instance, but all my instances are being managed by tf_aws_rds module, so if I add some parameter to module, all my instances will be altered. Which of course I don't want to do.

Do you have any ideas or working solutions on that?

Thanks a lot!
Grzegorz

### PR DESCRIPTION
**Pull request by gimoh**
Add two optional input variables, one to indicate an external parameter group should be used instead of the built-in one, and the other to specify the name of the group to use. For now, a single variable doesn't appear to be sufficient due to hashicorp/terraform#12570

Fixes #29

### CODE REVIEW

**Comment by gstlt** [comment]
Cool stuff! :)

**Comment by antonbabenko** [comment]
LGTM

**Comment by antonbabenko** [comment]
New release - https://github.com/terraform-community-modules/tf_aws_rds/releases/tag/v1.0.3

**Comment by gimoh** [comment]
yay 🎉 cheers guys!

**Pull request merged**
